name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        if: github.event_name != 'workflow_dispatch'
        run: gh release create ${{ github.ref_name }} --draft=true --generate-notes

  build-and-upload:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build extension
        run: pnpm build
      - name: Create ZIP
        run: pnpm zip
      - name: Upload assets
        if: github.event_name != 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: .output/*.zip

  publish-release:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish release
        if: github.event_name != 'workflow_dispatch'
        run: gh release edit ${{ github.ref_name }} --draft=false
